#!/usr/bin/env python3
"""Generate Codex CLI custom prompts from .claude/commands/ — the Codex analogue of the plugin.

Codex has NO plugin/marketplace system. Its closest extensibility for slash commands is
user-level custom prompts: a markdown file at `$CODEX_HOME/prompts/<name>.md` (default
`~/.codex/prompts/<name>.md`) becomes the `/<name>` command in the Codex TUI.

This script mirrors the workflow commands into self-contained Codex prompts so a Codex user
gets `/coord`, `/analyze-task`, `/dev`, … globally — even outside the agent-workspace repo.
`.claude/commands/` stays the single source of truth; rerun to regenerate.

Output: `.codex/prompts/<name>.md` in the repo. Install for global use:
    mkdir -p ~/.codex/prompts && cp .codex/prompts/*.md ~/.codex/prompts/

Usage:
    python3 scripts/build-codex-prompts.py            # (re)generate
    python3 scripts/build-codex-prompts.py --check     # verify in sync, no writes

Note: like the Claude plugin, these prompts deliver the command *entrypoints*. The full stateful
workflow (project brain, .agent/, .runtime/) still requires the agent-workspace repo + AGENTS.md.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMANDS = ROOT / ".claude" / "commands"
OUT = ROOT / ".codex" / "prompts"

# Commands that are Claude-plugin-specific and do NOT work as Codex prompts.
# `aw-init` scaffolds from ${CLAUDE_PLUGIN_ROOT} (Claude-only) and the Codex plugin ships only
# skills (no .agent/ /.runtime/ /CLAUDE.md to copy) — so a Codex /aw-init would point at nothing.
EXCLUDE = {"aw-init", "access"}


def purpose_of(text: str) -> str:
    """Extract the one-line purpose from a command file (## Purpose section, else first prose)."""
    m = re.search(r"##\s*Purpose\s*\n+(.+?)(?:\n\n|\n#)", text, re.S)
    if m:
        return " ".join(m.group(1).split())
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            return s
    return ""


def render_prompt(name: str, command_text: str) -> str:
    purpose = purpose_of(command_text)
    desc = (purpose[:117] + "...") if len(purpose) > 120 else purpose
    return (
        f"---\n"
        f"description: \"agent-workspace /{name} — {desc}\"\n"
        f"argument-hint: \"[request or args]\"\n"
        f"---\n\n"
        f"You are running the agent-workspace `/{name}` workflow command inside Codex.\n\n"
        f"Follow `.codex/AGENTS.md` (or `AGENTS.md`) routing and the framework rules. Route every\n"
        f"request through the coordinator model; do not bypass approval gates, security/secret rules,\n"
        f"or the task-analysis source-edit gate. If the agent-workspace framework files\n"
        f"(`.agent/`, `.runtime/`, `.claude/commands/{name}.md`) are present, defer to them as the\n"
        f"authoritative contract — this prompt is a portable mirror.\n\n"
        f"User input for this command: $ARGUMENTS\n\n"
        f"---\n"
        f"## Command contract (mirrored from .claude/commands/{name}.md)\n\n"
        f"{command_text.strip()}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify prompts match source, no writes")
    ap.add_argument("--force", action="store_true", help="overwrite even hand-edited prompts")
    args = ap.parse_args()
    from _genlib import Generator

    sources = sorted(p for p in COMMANDS.glob("*.md") if p.name != "README.md" and p.stem not in EXCLUDE)
    artifacts: dict[Path, str] = {}
    for src in sources:
        name = src.stem
        artifacts[OUT / f"{name}.md"] = render_prompt(name, src.read_text(encoding="utf-8"))

    readme = (
        "# Codex Prompts (generated)\n\n"
        "Generated by `scripts/build-codex-prompts.py` from `.claude/commands/`. Codex has no plugin\n"
        "marketplace; these are user-level custom prompts.\n\n"
        "## Install (global, all Codex projects)\n\n"
        "```bash\n"
        "mkdir -p ~/.codex/prompts && cp .codex/prompts/*.md ~/.codex/prompts/\n"
        "```\n\n"
        "Then in the Codex TUI: `/coord`, `/analyze-task`, `/dev`, `/qc`, … become available.\n\n"
        "These mirror the command entrypoints; the full stateful workflow still needs the\n"
        "agent-workspace repo + `AGENTS.md`. Do not edit these files by hand — rerun the generator.\n"
    )
    artifacts[OUT / "README.md"] = readme

    # Prompts present on disk but no longer generated (e.g. an excluded command) are stale.
    expected = set(artifacts)
    stale = [p for p in OUT.glob("*.md") if p not in expected] if OUT.exists() else []

    if args.check:
        drift = [p.relative_to(ROOT).as_posix() for p, exp in artifacts.items()
                 if (p.read_text(encoding="utf-8") if p.is_file() else None) != exp]
        drift += [p.relative_to(ROOT).as_posix() + " (stale)" for p in stale]
        if drift:
            print(f"[check] codex prompts out of sync: {drift} — run scripts/build-codex-prompts.py")
            return 1
        print(f"[check] codex prompts in sync ({len(sources)} commands)")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for p in stale:
        p.unlink()
    gen = Generator("build-codex-prompts", force=args.force)
    for path, content in artifacts.items():
        gen.write(path, content)
    gen.flush()
    if stale:
        print(f"Removed {len(stale)} stale prompt(s): {[p.name for p in stale]}")
    print(f"Codex prompts: {len(sources)} commands → {OUT.relative_to(ROOT)}/")
    print("  install: mkdir -p ~/.codex/prompts && cp .codex/prompts/*.md ~/.codex/prompts/")
    return gen.report()


if __name__ == "__main__":
    raise SystemExit(main())
